version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      nextauth:
        patterns:
          - "next-auth"
          - "@auth/*"
      testing:
        patterns:
          - "jest*"
          - "@jest/*"
          - "@testing-library/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
